error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: DEBUG

#spring:
#  main:
#    show-banner: false

#spring:
#  thymeleaf:
#    cache: false

#server:
#  port: 8000

#server:
#  port: 8443
#  ssl:
#    key-store: file:///path/to/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein


#logging:
#  level:
#    root: WARN
#    org:
#      springframework:
#        security: DEBUG

#logging:
#  level:
#  root: WARN
#  org.springframework.security: DEBUG

#logging:
#  path: /var/logs/
#  file: BookWorm.log
#  level:
#    root: WARN
#    org:
#      springframework:
#        security: DEBUG

#logging:
#  config:
#    classpath:logging-config.xml

#spring:
#  datasource:
#    url: jdbc:mysql://localhost/readinglist
#    username: dbuser
#    password: dbpass
#    driver-class-name: com.mysql.jdbc.Driver

#spring:
#  datasource:
#    jndi-name: java:/comp/env/jdbc/readingListDS

#amazon:
#  associateId: habuma-20

#spring:
#  profiles:
#    active: production



